replicaCount: 2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

image:
  registry: REGISTRY
  repository: REPONAME
  pullPolicy: Always
  tag: "latest"

serviceMonitor:
  enabled: true

podSecurityContext:
  sysctls:
      - name: net.core.somaxconn
        value: "32768"

service:
  type: LoadBalancer
  port: 8080 # ingress port
  ports:
    - name: http
      port: 8080
      protocol: tcp
    - name: quic
      port: 4242
      protocol: udp

ingress:
  enabled: false
  hosts:
    - host: ADDRESS
      router: private
      name: private

resources:
   limits:
     cpu: 1500m
     memory: 1024Mi
   requests:
     cpu: 1500m
     memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  http:
    port: 8080
  qsse:
    topics: ["t1", "t2", "t3", "t4"]
    port: 4242
    client_acceptor_count: 4
    client_acceptor_queue_size: 4
    event_distributor_count: 10
    event_distributor_queue_size: 10
    cleaning_interval: 2
  logger:
    level: "debug"
#  generator:
#    generators:
#      - topic: "topic"
#        event_size: 100
#        rate: 500
#      - topic: "people"
#        event_size: 500
#        rate: 200
#    identical_generators: false
#    count: 3
#    publish_address: "http://localhost:8080/event/publish"
#    timeout: 1000
#  subscriber:
#    topics:
#      - "topic"
#      - "people"
#    count: 2
#    server_address: "localhost:4242"