---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qsset-generator.fullname" . }}
  labels:
    {{- include "qsset-generator.labels" . | nindent 4 }}
{{- with .Values.config}}
data:
  config.yaml: |
    {{- toYaml . | nindent 4 }}
{{- end}}