{{- range $key, $value := .Values.service.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qsset-subscriber.fullname" $ }}-{{$value.name}}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "qsset-subscriber.labels" $ | nindent 4 }}
    type: {{ $value.name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: {{ $value.name }}
      protocol: {{ $value.protocol | upper }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
  selector:
    {{- include "qsset-subscriber.selectorLabels" $ | nindent 4 }}

{{ end }}