replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

image:
  registry: REGISTRY
  repository: REPO
  pullPolicy: Always
  tag: "latest"

ingress:
  enabled: false

service:
  type: None

resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 150m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


config:
  http:
    port: 8080
  qsse:
    topics: ["t1", "t2", "t3", "t4"]
    port: 4242
  logger:
    level: "debug"
  generator:
    generators:
      - topic: "t1"
        event_size: 100
        rate: 200
      - topic: "t2"
        event_size: 500
        rate: 500
      - topic: "t3"
        event_size: 1000
        rate: 1000
      - topic: "t4"
        event_size: 2000
        rate: 500
    identical_generators: false
    count: 3
    publish_address: "http://qsset-server-http:8080/event/publish"
    timeout: 1000
#  subscriber:
#    topics:
#      - "topic"
#      - "people"
#    count: 2
#    server_address: "localhost:4242"